#AutoIt3Wrapper_Au3Check_Parameters=-q -d -w 1 -w 2 -w 3 -w- 4 -w 5 -w 6 -w- 7
;~ #au3check -q -d -w 1 -w 2 -w 3 -w- 4 -w 5 -w 6 -w- 7
;~ Example 5 Automating chrome
;~ This example shows how to use UI Automation with chrome (later an example will come to put stuff in the html page)
;~ 1. Have chrome started with "--force-renderer-accessibility"
;~ 2. Check with chrome://accessibility in the adress bar if accessibility is on/off, turn it on
;~ a. or close all browsers and change in script the run command to the right path of the chrome.exe
;~
;~ Apparently google changed some stuff in chrome version 29 and seems not allways to return classname properly so sometimes
;~ harder to get the right element
;- Even worse on version 42 not returning UIA controltype or classnames for certain elements
;~ Version chrome 65

#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <WindowsConstants.au3>
#include <constants.au3>
#include <WinAPI.au3>
#AutoIt3Wrapper_Au3Check_Parameters=-q -d -w 1 -w 2 -w 3 -w- 4 -w 5 -w 6 -w- 7
;~ #au3check -q -d -w 1 -w 2 -w 3 -w- 4 -w 5 -w 6 -w- 7
#include <debug.au3>

#include "UIAWrappers.au3"

#AutoIt3Wrapper_UseX64=N  ;Should be used for stuff like tagpoint having right struct etc. when running on a 64 bits os

local $strChromeStartup="--force-renderer-accessibility"
local $strChromeExeFolder=@UserProfileDir & "\AppData\Local\Google\Chrome\Application\"
local $strChromeExe=$strChromeExeFolder & "chrome.exe "

if not fileexists($strChromeExe) Then
    $strChromeExeFolder=@ProgramFilesDir & "\Google\Chrome\Application\"
    $strChromeExe=$strChromeExeFolder & "chrome.exe "
EndIf

;~ Start chrome
if fileexists($strChromeExe) Then
    if not processexists("chrome.exe") Then
        run($strChromeExe & $strChromeStartup,"", @SW_MAXIMIZE )
        ProcessWait("chrome.exe")
        ;~ Just to give some time to start
        sleep(10000)
    endif
Else
    if not processexists("chrome.exe") Then
        consolewrite("No clue where to find chrome on your system, please start manually:" & @CRLF )
        consolewrite($strChromeExeFolder & @CRLF)
        consolewrite(@ProgramFilesDir & @CRLF)
;~      C:\Program Files (x86)\Google\Chrome\Application

        consolewrite($strChromeExe & $strChromeStartup & @CRLF)
        Exit
